//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Management_System_Userview.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        public int Food_ID { get; set; }
        public string Food_Name { get; set; }
    }
}
