//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Event_Management_System_Userview.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventDBEntities2 : DbContext
    {
        public EventDBEntities2()
            : base("name=EventDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking_Events> Booking_Events { get; set; }
        public virtual DbSet<BookingFlower> BookingFlowers { get; set; }
        public virtual DbSet<DecorationEquipment> DecorationEquipments { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<FoodItem> FoodItems { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
    }
}
